package yugioh.model.duel;

public enum Command {
    cardShow,
    selectMonster,
    selectOpponentMonster,
    selectSpell,
    selectOpponentSpell,
    selectField,
    selectOpponentField,
    selectHand,
    deselect,
    attack,
    cardShowSelected,
    nextPhase,
    summon,
    set,
    setCardPositionDefense,
    setCardPositionAttack,
    flipSummon,
    directAttack,
    activateEffect,
    ritualSummon,
    showGraveyard,
    showGraveyardOpponent,
    surrender,
}
